[package]
name = "blur-test-plugin"
version = "0.1.1"
edition = "2021"


[lib]
name = "my_test_plugin"
crate-type = ["cdylib"]


[dependencies]
blur-plugins-core = { git = "https://github.com/tobii-dev/blur-plugins-core", version = "0.1.2" }
